#
# Rakefile for the GATK 'better' workflow
# 
# copyright (c) 2010-2011 Hiroyuki MISHIMA
# ( missy at be.to / hmishima at nagasaki-u.ac.jp )
# see README.rdoc and LICENCE for detail 

load "#{File.dirname(__FILE__)}/Rakefile.helper"
load "#{File.dirname(__FILE__)}/Rakefile.invoke"

require 'rake/clean'
require 'pwrake/graph' if defined? Pwrake
Pwrake::Shell.nice = "nice -n 15" if defined? Pwrake

module Rakefile
  class Gatk
    WORKDIR    = "#{File.dirname(__FILE__)}/../Sample"
    BAM        = FileList["#{WORKDIR}/DRR000606.21.bam"]
    DEDUP_BAM  = suffix(BAM, ".bam" => ".dedup.bam")
    INTERVALS  = suffix(BAM, ".bam" => ".dedup.bam.intervals")
    REALIG     = suffix(BAM, ".bam" => ".dedup.realig.bam")
    REALIG_FIX = suffix(BAM, ".bam" => ".dedup.realig.fix.bam")
    RECAL      = suffix(BAM, ".bam" => ".dedup.realig.fix.bam.recal.csv")
    RECALBAM   = suffix(BAM, ".bam" => ".dedup.realig.fix.recal.bam")
    RECALBAI   = suffix(BAM, ".bam" => ".dedup.realig.fix.recal.bai")
    ALL_SNVS_RAW_VCF       = "#{WORKDIR}/all_snvs.raw.vcf"
    ALL_SNVS_FILTERED_VCF  = "#{WORKDIR}/all_snvs.filtered.vcf"
    ALL_INDELS_BED         = "#{WORKDIR}/all_indels.bed"
    ALL_INDELS_VCF         = "#{WORKDIR}/all_indels.vcf"
    ALL_INDELS_MASK_BED    = "#{WORKDIR}/all_indels.mask.bed"
  end
end

Rakefile::Gatk::BAM.each do |bam|
  CLEAN.include(suffix(bam, ".bam" => ".dedup*"),
                "#{Rakefile::Gatk::WORKDIR}/all_indels*",
                "#{Rakefile::Gatk::WORKDIR}/all_snvs*",)
  CLEAN.exclude("#{Rakefile::Gatk::WORKDIR}/all_snvs.filtered.vcf*",
                "#{Rakefile::Gatk::WORKDIR}/all_indels.vcf*",
                "#{Rakefile::Gatk::WORKDIR}/all_mask.bed*",)
  CLOBBER.include("#{Rakefile::Gatk::WORKDIR}/all_snvs.filtered.vcf*",
                  "#{Rakefile::Gatk::WORKDIR}/all_indels.vcf*",
                  "#{Rakefile::Gatk::WORKDIR}/all_mask.bed*",)
end

#
# GATK's "better" workflow rules
# (local realign and quality score recalibration)
#

desc "Picard MarkDuplicate: DeDup reads"
rule '.dedup.bam' =>
  [ suffix_proc(".dedup.bam" => ".bam") ] do |t|
  RakefileInvoke::Gatk.picard_markduplicate t
end

desc "GATK RealignerTargetCreater"
rule '.dedup.bam.intervals' =>
  [ suffix_proc(".bam.intervals" => ".bam") ] do |t|
  RakefileInvoke::Gatk.gatk_realigner_target_creater t
end

desc "GATK IndelRealigner"
rule '.dedup.realig.bam' =>
    [ suffix_proc(".dedup.realig.bam" => ".dedup.bam"),
      suffix_proc(".dedup.realig.bam" => ".dedup.bam.intervals")
    ] do |t|
  RakefileInvoke::Gatk.gatk_indel_realigner t
end

desc "Picard FixMateInformation"
rule '.dedup.realig.fix.bam' =>
  [ suffix_proc(".dedup.realig.fix.bam" => ".dedup.realig.bam") ] do |t|
  RakefileInvoke::Gatk.picard_fixmateinformation t
end

desc "GATK: CountCovariates"
rule '.dedup.realig.fix.bam.recal.csv' =>
  [ suffix_proc(".dedup.realig.fix.bam.recal.csv" =>
                ".dedup.realig.fix.bam") ] do |t|
  RakefileInvoke::Gatk.gatk_count_covariates t
end

desc "GATK: TableRecalibration"
rule '.dedup.realig.fix.recal.bam' =>
  [ suffix_proc(".dedup.realig.fix.recal.bam" =>
                ".dedup.realig.fix.bam"),
    suffix_proc(".dedup.realig.fix.recal.bam" =>
                ".dedup.realig.fix.bam.recal.csv") ] do |t|
  RakefileInvoke::Gatk.gatk_table_recalibration t
end

desc "Picard index: Generate index files for recalibrated BAMs"
rule '.dedup.realig.fix.recal.bai' =>
  [ suffix_proc(".dedup.realig.fix.recal.bai" =>
                ".dedup.realig.fix.recal.bam") ] do |t|
  RakefileInvoke::Gatk.picard_build_bam_index t
end

#
# GATK's "better" workflow rules
# (SNV and INDEL genotyping)
#

desc "GATK: UnifiedGenotyper for SNVs"
file Rakefile::Gatk::ALL_SNVS_RAW_VCF => Rakefile::Gatk::RECALBAI do |t|
   RakefileInvoke::Gatk.gatk_unifiedgenotyper t
end

desc "GATK: IndelGenotyperV2"
file Rakefile::Gatk::ALL_INDELS_VCF => Rakefile::Gatk::RECALBAI do |t|
   RakefileInvoke::Gatk.gatk_indelgenotyper_v2 t
end
file Rakefile::Gatk::ALL_INDELS_BED => Rakefile::Gatk::ALL_INDELS_VCF

desc "GATK: makeIndelMask"
file Rakefile::Gatk::ALL_INDELS_MASK_BED => Rakefile::Gatk::ALL_INDELS_BED do |t|
    RakefileInvoke::Gatk.gatk_make_indelmask t
end

desc "GATK: VariantFiltration"
file Rakefile::Gatk::ALL_SNVS_FILTERED_VCF =>
    [Rakefile::Gatk::ALL_SNVS_RAW_VCF, Rakefile::Gatk::ALL_INDELS_MASK_BED] do |t|
   RakefileInvoke::Gatk.gatk_variant_filtration t
end

#
# default task 
#

#task :default => Rakefile::Gatk::DEDUP_BAM
#task :default => Rakefile::Gatk::INTERVALS
#task :default => Rakefile::Gatk::REALIG
#task :default => Rakefile::Gatk::REALIG_FIX
#task :default => Rakefile::Gatk::RECAL
#task :default => Rakefile::Gatk::RECALBAM
#task :default => Rakefile::Gatk::RECALBAI
#task :default => Rakefile::Gatk::ALL_SNV_RAW_VCF
#task :default => Rakefile::Gatk::ALL_INDELS_VCF
#task :default => Rakefile::Gatk::ALL_INDELS_MASK_BED
task :default => Rakefile::Gatk::ALL_SNVS_FILTERED_VCF

#
# the graph task to output DAG graph
# DOT files can be converted to image files
# using Graphviz http://graphviz.org
#
task :gatk_graph => :default do
  #require "pwrake/graph"
  g = Pwrake::Graphviz.new
  g.trace
  g.write("graphviz.dot")
end
