#
# Rakefile for the Dindel workflow 
# 
# copyright (c) 2010-2011 Hiroyuki MISHIMA
# ( missy at be.to / hmishima at nagasaki-u.ac.jp )
# see README.rdoc and LICENCE for detail 

load "#{File.dirname(__FILE__)}/Rakefile.helper"
load "#{File.dirname(__FILE__)}/Rakefile.invoke"

require 'rake/clean'
require 'pwrake/graph' if defined? Pwrake
Pwrake::Shell.nice = "nice -n 15" if defined? Pwrake

module Rakefile
  class Dindel
    WORKDIR    = "#{File.dirname(__FILE__)}/../Sample"
    BAM        = FileList["#{WORKDIR}/DRR000606.21.bam"]
  end
end

Rakefile::Dindel::BAM.each do |file|
  CLEAN.include("#{suffix(file , ".bam" => "")}.dindel.output_regions.*",
                "#{suffix(file , ".bam" => "")}.dindel.realign_windows.*",
                "#{suffix(file , ".bam" => "")}.dindel.libraries.txt",
                "#{suffix(file , ".bam" => "")}.dindel.output_files.txt",
                "#{suffix(file , ".bam" => "")}.dindel.realign_windows",
                "#{suffix(file , ".bam" => "")}.dindel.variants.txt*",)
  CLOBBER.include("#{suffix(file , ".bam" => "")}.dindel.vcf",)
end

##
## DINDEL stages
##

# DINDEL stage 1
#
desc "DINDEL stage1"
rule ".dindel.variants.txt" => 
  [ suffix_proc(".dindel.variants.txt" => ".bam") ] do |t|
  opts = {:prefix => suffix(t.name, ".variants.txt" => "")}
  RakefileInvoke::Dindel.dindel_stage1(t, opts)
end

rule ".dindel.libraries.txt" =>
  [ suffix_proc(".dindel.libraries.txt" => ".bam") ]

Rakefile::Dindel::BAM.each do |bam|
task :stage1 => suffix(bam, ".bam" => ".dindel.variants.txt")
end

# DINDEL stage 2
#
desc "DINDEL stage2"
rule ".dindel.realign_windows" =>
  [ suffix_proc(".dindel.realign_windows" => ".dindel.variants.txt"),
    suffix_proc(".dindel.realign_windows" => ".dindel.libraries.txt"),
  ] do |t|
  RakefileInvoke::Dindel.make_windows t
end

Rakefile::Dindel::BAM.each do |bam|
  task :stage2 => suffix(bam, ".bam" => ".dindel.realign_windows")
end
# DINDEL stage 3
#

desc "DINDEL stage3"
task :stage3 => :stage2 do
  Rakefile::Dindel::BAM.each do |bam|
    FileList["#{bam.sub(/\.bam$/, ".dindel.realign_windows")}.*.txt"].each do |fn|
      target = fn.sub(/\.realign_windows\./, ".output_regions.").
                  sub(/\.txt$/, ".glf.txt")
      file target =>
        [  fn,
           fn.sub(/\.dindel\.realign_windows\..*/, ".bam"),
           fn.sub(/\.dindel\.realign_windows\..*/, ".dindel.libraries.txt"),
        ] do |t|
        RakefileInvoke::Dindel.dindel_stage3 t
      end
      task :stage3_invoke => target
    end
  end
  (task :stage3_invoke).invoke
end

# DINDEL stage 4
#

## stage 4a
desc "DINDEL stagr4a (build result filelists)"
task :stage4a => :stage3 do 
  Rakefile::Dindel::BAM.each do |bam|
    file suffix(bam, ".bam" => ".dindel.output_files.txt") =>
      FileList["#{bam.sub(/\.bam$/, ".dindel.output_regions")}.*.glf.txt"] do |t|
      RakefileInvoke::Dindel.dindel_stage4_filelist t
    end
    file :stage4a_invoke => suffix(bam, ".bam" => ".dindel.output_files.txt")
  end
  (task :stage4a_invoke).invoke
end
Rakefile::Dindel::BAM.each do |bam|
  file suffix(bam, ".bam" => ".dindel.output_files.txt") => :stage4a
end

## stage 4b
rule ".dindel.vcf" =>
  [ suffix_proc(".dindel.vcf" => ".dindel.output_files.txt") ] do |t|
  RakefileInvoke::Dindel.indel_stage4 t
end

desc "DINDEL stage4b (integrate results)"
Rakefile::Dindel::BAM.each do |bam|
  file :stage4b => [suffix(bam, ".bam" => ".dindel.vcf")]
end

#
# default task
#

#task :default => :stage1 
#task :default => :stage2 
#task :default => :stage3 
#task :default => :stage4a 
task :default => :stage4b 

#
# the graph task to output DAG graph
# DOT files can be converted to image files
# using Graphviz http://graphviz.org
#
task :dindel_graph => :default do
  #require "pwrake/graph"
  g = Pwrake::Graphviz.new
  g.trace
  g.write("graphviz.dot")
end
